sudo: false
language: python
python:
  - "3.8"
install:
  - pip install -U pip
  - pip install -e .
  - pip install pytest>=5 pytest-asyncio pytest-cov pytest-mock coveralls
script:
  - pytest -v --cov=src/cardinal tests
after_success:
  - coveralls
  - .travis/dockerhub-trigger.sh
