sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pytest-mock coveralls
env:
  - PYTHONPATH=src
script:
  - pytest -v --cov=src/cardinal tests
after_success: coveralls