sudo: false
language: python
python:
  - "3.5"
install:
  - pip install -U pip
  - pip install -e .
  - pip install pytest pytest-asyncio pytest-mock
script:
  - pytest -v tests
after_success:
  - .travis/dockerhub-trigger.sh
