language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - PYTHONPATH=src
script:
  - python -m unittest discover -s test
  - coverage run --source=src -m unittest discover -s test