sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov coveralls
env:
  - PYTHONPATH=src
script:
  - pytest --cov=src/cardinal test
after_success: coveralls