language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
env:
  - PYTHONPATH=src
script: coverage run -m unittest discover -s test && coveralls