"""Role ID should be unique

Revision ID: 25d0f68d0698
Revises: 313ce21eb461
Create Date: 2018-12-10 17:04:30.274466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25d0f68d0698"
down_revision = "313ce21eb461"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_mute_guilds_role_id"), "mute_guilds", ["role_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_mute_guilds_role_id"), "mute_guilds", type_="unique")
    # ### end Alembic commands ###
