"""Add tables for DB-based muting

Revision ID: 313ce21eb461
Revises: 0002ca860468
Create Date: 2018-12-10 14:53:50.525225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313ce21eb461'
down_revision = '0002ca860468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mute_guilds',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', name=op.f('pk_mute_guilds'))
    )
    op.create_table('mute_users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['mute_guilds.guild_id'], name=op.f('fk_mute_users_guild_id_mute_guilds')),
    sa.PrimaryKeyConstraint('user_id', 'guild_id', name=op.f('pk_mute_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mute_users')
    op.drop_table('mute_guilds')
    # ### end Alembic commands ###
