"""Index muted_until column for use in filters

Revision ID: 52d93745fa71
Revises: dc0db050f230
Create Date: 2018-12-13 13:53:58.895770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d93745fa71'
down_revision = 'dc0db050f230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mute_users_muted_until'), 'mute_users', ['muted_until'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mute_users_muted_until'), table_name='mute_users')
    # ### end Alembic commands ###
